sudo: false
language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip
env:
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=arm64
  - GOOS=linux GOARCH=mips
  - GOOS=linux GOARCH=mipsle
  - GOOS=darwin GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=darwin GOARCH=arm
  - GOOS=darwin GOARCH=arm64
  - GOOS=freebsd GOARCH=386
  - GOOS=freebsd GOARCH=amd64
  - GOOS=freebsd GOARCH=arm
  - GOOS=freebsd GOARCH=arm64
  - GOOS=freebsd GOARCH=mips
  - GOOS=freebsd GOARCH=mipsle
  - GOOS=windows GOARCH=386
  - GOOS=windows GOARCH=amd64
  - GOOS=windows GOARCH=arm
  - GOOS=windows GOARCH=amd64
